linters-settings:
  lll:
    line-length: 130
  # Values modified to handle existing v.Run() func
  gocyclo:
    min-complexity: 32
  maintidx:
    under: 17
linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - golint
    - gomnd
    - gomoddirectives
    - interfacer
    - maligned
    - nilnil
    - paralleltest
    - predeclared
    - scopelint
    - testpackage
    - varnamelen
    - wrapcheck
